import 'package:home/data/models/image.dart';
import 'package:packages/exports.dart';

part 'show_response.g.dart';

@JsonSerializable()
class ShowResponse extends Equatable {
  final int? id;
  final String? url;
  final String? name;
  final Image? image;

  const ShowResponse({
    this.id,
    this.url,
    this.name,
    this.image,
  });

  @override
  List<Object?> get props => [
        id,
        url,
        name,
        image,
      ];

  factory ShowResponse.fromJson(Map<String, dynamic> json) =>
      _$ShowResponseFromJson(json);

  Map<String, dynamic> toJson() => _$ShowResponseToJson(this);
}


  // int? id;
  // String? url;
  // String? name;
  // String? type;
  // String? language;
  // List<String>? genres;
  // String? status;
  // int? runtime;
  // int? averageRuntime;
  // String? premiered;
  // String? ended;
  // String? officialSite;
  // Schedule? schedule;
  // Rating? rating;
  // int? weight;
  // Network? network;
  // Null? webChannel;
  // Null? dvdCountry;
  // Externals? externals;
  // Image? image;
  // String? summary;
  // int? updated;
  // Links? lLinks;

  // Autogenerated({
  //   this.id,
  //   this.url,
  //   this.name,
  //   this.type,
  //   this.language,
  //   this.genres,
  //   this.status,
  //   this.runtime,
  //   this.averageRuntime,
  //   this.premiered,
  //   this.ended,
  //   this.officialSite,
  //   this.schedule,
  //   this.rating,
  //   this.weight,
  //   this.network,
  //   this.webChannel,
  //   this.dvdCountry,
  //   this.externals,
  //   this.image,
  //   this.summary,
  //   this.updated,
  //   this.lLinks,
  // });