// Mocks generated by Mockito 5.2.0 from annotations
// in home/test/presentation/controller/search_controller_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:entities/shows/entities/show.dart' as _i5;
import 'package:home/domain/use_cases/search_shows_use_case.dart' as _i3;
import 'package:home/infrastructure/data_sources/search_shows_data_source.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeSearchShowsDataSource_0 extends _i1.Fake
    implements _i2.SearchShowsDataSource {}

/// A class which mocks [SearchShowsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchShowsUseCase extends _i1.Mock
    implements _i3.SearchShowsUseCase {
  MockSearchShowsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SearchShowsDataSource get searchShowsDataSource =>
      (super.noSuchMethod(Invocation.getter(#searchShowsDataSource),
              returnValue: _FakeSearchShowsDataSource_0())
          as _i2.SearchShowsDataSource);
  @override
  _i4.Future<List<_i5.Show>> call({String? query}) =>
      (super.noSuchMethod(Invocation.method(#call, [], {#query: query}),
              returnValue: Future<List<_i5.Show>>.value(<_i5.Show>[]))
          as _i4.Future<List<_i5.Show>>);
}
